name: Build and release

#on: workflow_dispatch

on:
  workflow_dispatch:
  push:
    tags:
      - "v*.*.*"

jobs:
  release:
    name: Release - ${{ matrix.platform.os }}
    strategy:
      matrix:
        platform:
          - os: ubuntu-20.04
            target: x86_64-unknown-linux-gnu
            bin: aid
            name: aid-x86_64-linux.tar.gz

    runs-on: ${{ matrix.platform.os }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Get required packages (Linux only)
        if: contains(matrix.platform.os, 'ubuntu')
        run: sudo apt install build-essential curl clang llvm pkg-config libssl-dev
      - name: Cache cargo & target directories
        uses: Swatinem/rust-cache@v2
      - name: Build binary
        uses: houseabsolute/actions-rust-cross@v0
        with:
          target: ${{ matrix.platform.target }}
          args: "--release"
      - name: Upload artifact (Ubuntu)
        if: contains(matrix.platform.os, 'ubuntu')
        uses: actions/upload-artifact@v3.1.3
        with:
          path: target/**/release/aid
  publish:
    needs: [release]
    name: Publish
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Download artifacts
        uses: actions/download-artifact@v3
        with:
          path: target/
      - name: Publish to GitHub Releases
        uses: softprops/action-gh-release@v1
        with:
          files: target/**
