on: workflow_dispatch

jobs:
  release:
    name: release ${{ matrix.target }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        target: [x86_64-unknown-linux-musl]
        include:
          - target: x86_64-unknown-linux-musl
            archive: tar.gz
    steps:
      - name: Install LLVM and Clang
        uses: KyleMayes/install-llvm-action@v1
        with:
          version: "16.0"
      - name: Set LIBCLANG_PATH
        run: echo "LIBCLANG_PATH=$(pwd)" >> "$GITHUB_ENV"
        working-directory: ${{ env.LLVM_PATH }}/lib
      - name: Link libclang
        run: sudo ln -sf ${{ env.LLVM_PATH }}/lib/libclang.so.16.0.4 /usr/lib/libclang.so
      - name: echo LIBCLANG_PATH
        run: echo "LIBCLANG_PATH=$LIBCLANG_PATH"
      - uses: actions/checkout@master
      - name: Compile and release
        uses: rust-build/rust-build.action@v1.4.4
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          RUSTTARGET: ${{ matrix.target }}
          EXTRA_FILES: "README.md LICENSE.txt"
