on: workflow_dispatch

jobs:
  release:
    name: release ${{ matrix.target }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        target: [x86_64-unknown-linux-musl]
        include:
          - target: x86_64-unknown-linux-musl
            archive: tar.gz
    steps:
      - name: Install toolchain dependencies
        shell: bash
        run: |
          apt-get update && apt-get install -y build-essential curl clang llvm
      - uses: actions/checkout@master
      - name: Compile and release
        uses: rust-build/rust-build.action@v1.4.4
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          RUSTTARGET: ${{ matrix.target }}
          EXTRA_FILES: "README.md LICENSE.txt"
