on: workflow_dispatch

jobs:
  release:
    name: release ${{ matrix.target }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        target: [x86_64-unknown-linux-musl]
        include:
          - target: x86_64-unknown-linux-musl
            archive: tar.gz
    steps:
      - name: Install LLVM and Clang
        uses: KyleMayes/install-llvm-action@v1
        with:
          version: "16.0"
      - name: Symlink libclang.so (Linux)
        run: sudo cp -va * /usr/lib/
        working-directory: ${{ env.LLVM_PATH }}/lib
      - uses: actions/checkout@master
      - name: Compile and release
        uses: rust-build/rust-build.action@v1.4.4
        env:
          LIBCLANG_PATH: ${{ env.LLVM_PATH }}/lib
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          RUSTTARGET: ${{ matrix.target }}
          EXTRA_FILES: "README.md LICENSE.txt"
